movie_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('movie/<slug:slug>', views.DetailMovie.as_view(), name='movie-detail'),
    path('movie', views.ListMovie.as_view()),
    path('directors', views.ListDirector.as_view(), name='all_directors'),
    path('directors/<slug:slug>', views.DetailDirector.as_view(), name='director-detail'),
    path('actors', views.ListActor.as_view(), name='all_actors'),
    path('actors/<slug:slug>', views.DetailActor.as_view(), name='actor-detail'),
]

movie_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('', include('movie_app.urls'))

]

movie_app/models.py
from django.db import models
from django.urls import reverse
from pytils.translit import slugify
from django.core.validators import MaxValueValidator, MinValueValidator
import datetime


class DressingRoom(models.Model):
    floor = models.IntegerField()
    numbers = models.IntegerField()

    def __str__(self):
        return f'Этаж {self.floor} Комната {self.numbers}'


class Actor(models.Model):
    FEMALE = 'F'
    MALE = 'M'
    GENDER = [
        (FEMALE, 'Женщина'),
        (MALE, 'Мужчина'),
    ]
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    gender = models.CharField(max_length=1, default=MALE, choices=GENDER)
    slug = models.SlugField(default='', null=False, db_index=True, blank=True)
    dressing = models.OneToOneField(DressingRoom, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_url(self):
        return reverse('actor-detail', args=[self.slug, ])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.first_name + self.last_name)
        super(Actor, self).save(*args, **kwargs)


class Director(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    director_email = models.EmailField(blank=True)
    slug = models.SlugField(default='', null=False, db_index=True, blank=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_url(self):
        return reverse('director-detail', args=[self.slug, ])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.first_name + self.last_name)
        super(Director, self).save(*args, **kwargs)


class Movie(models.Model):
    RUB = 'RUB'
    USD = 'USD'
    EUR = 'EUR'
    NOW_YEAR = datetime.date.today().year
    CURRENCY_CHOICES = [
        (EUR, 'Euro'),
        (USD, 'Dollar'),
        (RUB, 'Rubles'),
    ]

    currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default=RUB)
    name = models.CharField(max_length=40)
    rating = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(100)])  # от скольки до скольки принимать значения
    year = models.IntegerField(null=True, blank=True,  # бланк отвечает за возможность сохранить пустое поле
                               validators=[MinValueValidator(1950), MaxValueValidator(NOW_YEAR)],
                               default=2022)
    budget = models.IntegerField(validators=[MinValueValidator(1)])
    slug = models.SlugField(default='', null=False, db_index=True)
    director = models.ForeignKey(Director, on_delete=models.PROTECT,
                                 null=True)  # связь с таблицей Director (один ко многим)
    actors = models.ManyToManyField(Actor)

    def __str__(self):
        return f'{self.name} - {self.rating}%'

    def get_url(self):
        return reverse('movie-detail', args=[self.slug, ])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Movie, self).save(*args, **kwargs)

movie_app/views.py
from django.shortcuts import render, get_object_or_404
from .models import Movie, Director, Actor
from django.db.models import F, Sum, Max, Min, Count, Avg, Value
from django.views.generic import ListView, DetailView


def index(request):
    movies = Movie.objects.all()
    actors = Actor.objects.all()
    directors = Director.objects.all()

    return render(request, 'movie_app/index.html', {
        'movies': movies,
        'actors': actors,
        'directors': directors,

    })


class ListMovie(ListView):
    template_name = 'movie_app/all_movies.html'
    context_object_name = 'movies'
    model = Movie


class DetailMovie(DetailView):
    template_name = 'movie_app/one_movie.html'
    context_object_name = 'movie'
    model = Movie


class ListDirector(ListView):
    template_name = 'movie_app/all_directors.html'
    context_object_name = 'directors'
    model = Director


class DetailDirector(DetailView):
    template_name = 'movie_app/one_director.html'
    model = Director
    context_object_name = 'director'


class ListActor(ListView):
    template_name = 'movie_app/all_actors.html'
    model = Actor
    context_object_name = 'actors'


class DetailActor(DetailView):
    template_name = 'movie_app/one_actor.html'
    model = Actor
    context_object_name = 'actor'

movie_app/templates/movie_app/all_actors.html
{% extends 'movie_app/base.html' %}

{% block title %}
    Список режиссеров
{% endblock %}

{% block content %}
    <h1>Список актеров</h1>
    {% for actor in actors %}
        <h3><a href="{{ actor.get_url }}">{{ actor }}</a></h3>

    {% endfor %}

{% endblock %}

movie_app/templates/movie_app/all_directors.html
{% extends 'movie_app/base.html' %}

{% block title %}
    Список режиссеров
{% endblock %}

{% block content %}
    <h1>Список режисеров</h1>
    {% for director in directors %}
        <h3>
            <a href="{{ director.get_url }}">{{ director }}</a>
        </h3>

    {% endfor %}
{% endblock %}

movie_app/templates/movie_app/all_movies.html
{% extends 'movie_app/base.html' %}
{% block title %}
    Все фильмы
{% endblock %}
{% block content %}

    <h2>Список фильмов</h2>
        {% for movie in movies %}
            <h3>
                <a href="{{ movie.get_url }}">{{ movie.name }}</a> рейтинг - {{ movie.rating }} год
                    - {{ movie.year }}
            </h3>
        {% endfor %}

{% endblock %}

movie_app/templates/movie_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'movie_app/base.css' %}">
</head>
    {% include 'movie_app/include/navbar.html' %}

<body>
{% block content %} {% endblock %}
</body>
</html>

movie_app/templates/movie_app/include/navbar.html
<nav>
  <a href="/admin">ADMIN</a> |
  <a href="/">ГЛАВНАЯ</a> |
  <a href="/movie">ФИЛЬМЫ</a> |
  <a href="/directors">РЕЖИСЕРЫ</a> |
  <a href="/actors">АКТЕРЫ</a> |
</nav>

movie_app/templates/movie_app/index.html
{% extends 'movie_app/base.html' %}
{% block title %}
    Все фильмы
{% endblock %}
{% block content %}
    <h2><a href="directors">Список всех режиссеров</a></h2>
    <a href="movie"><h2>Список всех фильмов</h2></a>
    <a href="actors"><h2>Список всех актеров</h2></a>
{% endblock %}

movie_app/templates/movie_app/one_actor.html
{% extends 'movie_app/base.html' %}

{% block title %}
    {{ actor }}
{% endblock %}

{% block content %}
    <h1>АКТЕР</h1>
    <h2>{{ actor.first_name }} {{ actor.last_name }}</h2>

    <hr>
    <h2>Список фильмов:</h2>
    {% for movie in actor.movie_set.all %}
        <h3>
            <a href="{{ movie.get_url }}">
                {{ movie.name }} ({{ movie.year }})
            </a>
        </h3>

    {% endfor %}
{% endblock %}

movie_app/templates/movie_app/one_director.html
{% extends 'movie_app/base.html' %}

{% block title %}
    {{ director }}
{% endblock %}

{% block content %}
    <h1>РЕЖИССЕР</h1>
    <h2>{{ director.first_name }} {{ director.last_name }}</h2>
    {% if director.director_email %}
        <h2>Почта:{{ director.director_email }}</h2>
    {% endif %}
    <hr>
    <h1>Список фильмов:</h1>
    {% for movie in director.movie_set.all %}
        <h3>
            <a href="{{ movie.get_url }}">
                {{ movie }}
            </a>
        </h3>
    {% endfor %}

{% endblock %}

movie_app/templates/movie_app/one_movie.html
{% extends 'movie_app/base.html' %}
{% load my_filter %}
{% block title %} Информация о фильме {{ movie.name }}{% endblock %}

{% block content %}
    <h1>Информация о фильме - {{ movie.name }} ({{ movie.year }})</h1>
    <h2>Режиссер - <a href="{{ movie.director.get_url }}">{{ movie.director }}</a></h2>
    <h2>Рейтинг - {{ movie.rating }}
    <h2>Бюджет фильма - {{ movie.budget }}{{ movie.currency }}</h2>
    <hr>
    <h1>Список актеров</h1>
    {% for actor in movie.actors.all %}

        <h3><a href="{{ actor.get_url }}">{{ actor }}</a></h3>

    {% endfor %}

{% endblock %}